server {
    listen 3000;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # 禁用浏览器缓存，确保总是加载最新代码
    add_header Cache-Control "no-store, no-cache, must-revalidate" always;
    add_header Pragma "no-cache" always;
    add_header Expires "0" always;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass http://gateway:8090;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}