# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msp_node.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emsp_node.proto\x12\x08msp_node\"\x96\x02\n\x12\x45xecuteTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x11\n\ttask_type\x18\x02 \x01(\t\x12\x38\n\x06inputs\x18\x03 \x03(\x0b\x32(.msp_node.ExecuteTaskRequest.InputsEntry\x12@\n\nparameters\x18\x04 \x03(\x0b\x32,.msp_node.ExecuteTaskRequest.ParametersEntry\x1a-\n\x0bInputsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"f\n\x13\x45xecuteTaskResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x0e\n\x06result\x18\x04 \x01(\t\x12\r\n\x05\x65rror\x18\x05 \x01(\t\"\x14\n\x12HealthCheckRequest\"7\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\t2\xa1\x01\n\x07MSPNode\x12J\n\x0b\x45xecuteTask\x12\x1c.msp_node.ExecuteTaskRequest\x1a\x1d.msp_node.ExecuteTaskResponse\x12J\n\x0bHealthCheck\x12\x1c.msp_node.HealthCheckRequest\x1a\x1d.msp_node.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msp_node_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXECUTETASKREQUEST_INPUTSENTRY._options = None
  _EXECUTETASKREQUEST_INPUTSENTRY._serialized_options = b'8\001'
  _EXECUTETASKREQUEST_PARAMETERSENTRY._options = None
  _EXECUTETASKREQUEST_PARAMETERSENTRY._serialized_options = b'8\001'
  _globals['_EXECUTETASKREQUEST']._serialized_start=29
  _globals['_EXECUTETASKREQUEST']._serialized_end=307
  _globals['_EXECUTETASKREQUEST_INPUTSENTRY']._serialized_start=211
  _globals['_EXECUTETASKREQUEST_INPUTSENTRY']._serialized_end=256
  _globals['_EXECUTETASKREQUEST_PARAMETERSENTRY']._serialized_start=258
  _globals['_EXECUTETASKREQUEST_PARAMETERSENTRY']._serialized_end=307
  _globals['_EXECUTETASKRESPONSE']._serialized_start=309
  _globals['_EXECUTETASKRESPONSE']._serialized_end=411
  _globals['_HEALTHCHECKREQUEST']._serialized_start=413
  _globals['_HEALTHCHECKREQUEST']._serialized_end=433
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=435
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=490
  _globals['_MSPNODE']._serialized_start=493
  _globals['_MSPNODE']._serialized_end=654
# @@protoc_insertion_point(module_scope)
