# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from msp_node.protos import msp_node_pb2 as msp__node__pb2


class MSPNodeStub(object):
    """MSP节点服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTask = channel.unary_unary(
                '/msp_node.MSPNode/ExecuteTask',
                request_serializer=msp__node__pb2.ExecuteTaskRequest.SerializeToString,
                response_deserializer=msp__node__pb2.ExecuteTaskResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/msp_node.MSPNode/HealthCheck',
                request_serializer=msp__node__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=msp__node__pb2.HealthCheckResponse.FromString,
                )


class MSPNodeServicer(object):
    """MSP节点服务
    """

    def ExecuteTask(self, request, context):
        """执行任务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MSPNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTask,
                    request_deserializer=msp__node__pb2.ExecuteTaskRequest.FromString,
                    response_serializer=msp__node__pb2.ExecuteTaskResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=msp__node__pb2.HealthCheckRequest.FromString,
                    response_serializer=msp__node__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'msp_node.MSPNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MSPNode(object):
    """MSP节点服务
    """

    @staticmethod
    def ExecuteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/msp_node.MSPNode/ExecuteTask',
            msp__node__pb2.ExecuteTaskRequest.SerializeToString,
            msp__node__pb2.ExecuteTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/msp_node.MSPNode/HealthCheck',
            msp__node__pb2.HealthCheckRequest.SerializeToString,
            msp__node__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
