spring:
  application:
    name: msp-node-manager
  datasource:
    url: jdbc:mysql://localhost:3306/msp_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: msp
    password: msp123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8082